import { parse } from "@std/yaml";
import {
  type CatalogV2,
  isComposite,
} from "../../../../site/src/lib/shared/taxonomy-schema.ts";

const q = (s: string) => JSON.stringify(s);
const list = (xs: string[]) => `[${xs.join(", ")}]`;

/** Deterministic emitter: fixed section order, vocab sorted by slug, tasks sorted by id. */
export function emitCatalogYaml(c: CatalogV2): string {
  const bySlug = <T extends { slug: string }>(xs: T[]) =>
    [...xs].sort((a, b) => a.slug.localeCompare(b.slug));
  let o =
    "# Task taxonomy, schema version 2. Authoritative for the SITE only.\n";
  o +=
    "# NOT part of the task_set hash: editing this file and re-syncing never\n";
  o +=
    "# invalidates a benchmark. Generated by the refresh-task-taxonomy pipeline;\n";
  o +=
    "# facets come from pipeline/enriched-tags.json and tag definitions from\n";
  o += "# pipeline/facet-definitions.ts. Hand-edit only the overrides here.\n";
  o += "schema_version: 2\n\ngroups:\n";
  for (const g of bySlug(c.groups)) {
    o += `  - slug: ${g.slug}\n    name: ${q(g.name)}\n    description: ${
      q(g.description)
    }\n`;
  }
  o += "\nfamilies:\n";
  for (const f of bySlug(c.families)) {
    o += `  - slug: ${f.slug}\n    name: ${q(f.name)}\n    description: ${
      q(f.description)
    }\n`;
  }
  o += "\ntags:\n";
  for (const t of bySlug(c.tags)) {
    o += `  - slug: ${t.slug}\n    family: ${t.family}\n    name: ${
      q(t.name)
    }\n    description: ${q(t.description)}\n`;
    if (t.hidden_by_default) o += `    hidden_by_default: true\n`;
  }
  o += "\naliases:\n";
  for (const a of [...c.aliases].sort((x, y) => x.from.localeCompare(y.from))) {
    o += `  - { from: ${a.from}, to: ${a.to}${
      a.note ? `, note: ${q(a.note)}` : ""
    } }\n`;
  }
  o += "\noverrides:\n";
  if (c.overrides.length === 0) o += "  []\n";
  for (
    const ov of [...c.overrides].sort((x, y) => x.task.localeCompare(y.task))
  ) {
    o += `  - { task: ${ov.task}, group: ${ov.group}, rule: ${
      q(ov.rule)
    }, reason: ${q(ov.reason)} }\n`;
  }
  o += "\ntasks:\n";
  for (const id of Object.keys(c.tasks).sort()) {
    const e = c.tasks[id];
    if (!e) continue;
    if (isComposite(e)) {
      o += `  ${id}:\n    group: ${e.group}\n    donors: ${
        list(e.donors)
      }\n    derived_facets: ${list(e.derived_facets)}\n    local_facets: ${
        list(e.local_facets)
      }\n    min_bc_version: ${e.min_bc_version}\n`;
    } else {
      o += `  ${id}:\n    group: ${e.group}\n    facets: ${
        list(e.facets)
      }\n    min_bc_version: ${e.min_bc_version}\n`;
    }
  }
  return o;
}

export function parseCatalogYaml(text: string): CatalogV2 {
  const doc = parse(text) as CatalogV2;
  doc.aliases ??= [];
  doc.overrides ??= [];
  for (const e of Object.values(doc.tasks)) {
    if (isComposite(e)) {
      e.derived_facets ??= [];
      e.local_facets ??= [];
    }
  }
  return doc;
}
