name: Task Audits

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Run id-audit
        run: deno task id-audit

      - name: Run taxonomy-audit
        run: deno task taxonomy-audit
